"""buckets and objects models

Revision ID: f4350ae50e38
Revises: 9db27c699480
Create Date: 2026-09-03 10:32:26.848341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4350ae50e38'
down_revision: Union[str, Sequence[str], None] = '9db27c699480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buckets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=63), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buckets_name'), 'buckets', ['name'], unique=True)
    op.create_table('objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=1024), nullable=False),
    sa.Column('etag', sa.String(length=64), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('bucket_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bucket_id'], ['buckets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bucket_id', 'key', name='uq_bucket_key')
    )
    op.create_index(op.f('ix_objects_key'), 'objects', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_objects_key'), table_name='objects')
    op.drop_table('objects')
    op.drop_index(op.f('ix_buckets_name'), table_name='buckets')
    op.drop_table('buckets')
    # ### end Alembic commands ###
